/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Web3Account: typeof import('./src/components/Web3Account.vue')['default']
    Web3TX: typeof import('./src/components/Web3TX.vue')['default']
  }
}
